config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :trips do
    resources :locations
  end
 
  resources :locations do
    resources :addresses
  end

  resources :signup

  resources :newsletter, only: [:new, :create]

  get '/rails/mailers', to: "rails/mailers#index"
  get '/rails/mailers/*path', to: "rails/mailers#preview"


end

app/models/trip.rb
class Trip < ApplicationRecord
  validates_presence_of :name

  belongs_to :user
  has_many :locations
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @title = 'Trips'
    @trips = current_user.trips.paginate(page: params[:page], per_page: 3)
    flash[:info] = 'Welcome To The Trip Tracker'
  end

  def show
    @title = current_user.trips.name
    @locations = @trip.locations.all
  end

  def new
    @title = 'Add New Trip'
    @trip = current_user.trips.new
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.save
      flash[:success] = 'New Trip Created'
      redirect_to trip_path(@trip)
    else
      flash[:error] = 'Please Try Again'
      render :new
    end
  end

  def edit
    @title = 'Edit This Trip'
  end

  def update
    if @trip.update(trip_params)
      flash[:success] = 'Trip Updated'
      redirect_to trip_path(@trip)
    else
      flash[:error] = 'Please Try Again'
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private
    def trip_params
      params.require(:trip).permit(:name)
    end

    def set_trip
      @trip = Trip.find(params[:id])
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
  <div class='field margin'>
    <div class='card'>
      <h3><%= f.label :name %></h3>
      <h5><%= f.text_field :name %></h5>
    </div>
    <br />
  </div>

  <%= f.submit 'Submit', class: 'btn orange white-text margin'%>
<% end %>

app/views/trips/edit.html.erb
<%= render(partial: 'form') %>
<br />
<%= link_to 'Back', trips_path, class: 'btn orange white-text' %>

app/views/trips/index.html.erb
<div class='field margin'>
  <% @trips.each do |trip| %>
    <div class='col s12 m3 card'>
      <h5><%= trip.name %></h5>
      <%= link_to 'Show', trip_path(trip), class: 'btn orange white-text margin' %>
      <%= link_to 'Locations', trip_locations_path(trip), class: 'btn orange white-text margin' %>
    </div>
  <% end %>
</div>

<%= link_to 'New Trip', new_trip_path, class: 'btn orange white-text margin' %>

<div class=''>
  <%= will_paginate @trip %>
</div>

app/views/trips/new.html.erb
<%= render(partial: 'form') %>

<%= link_to 'Back', :back, class: 'btn orange white-text margin' %>

app/views/trips/show.html.erb
<ul>
  <h3 class='field margin'>
    <div class='card'>
      <li>Name: <%= @trip.name %> </li>
    </div>
  </h3>
    <li>
      <%= link_to 'Edit', edit_trip_path(@trip), class: 'btn orange white-text' %>
      <%= link_to 'Delete', trip_path(@trip), method: :delete, data: {confirm: 'Really Delete?'}, class: 'btn orange white-text' %>
    </li>
</ul>

<%= link_to 'Back', :back, class: 'btn orange white-text' %>