config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :trips do
    resources :locations
  end
 
  resources :locations do
    resources :addresses
  end

  resources :signup

  resources :newsletter, only: [:new, :create]

  get '/rails/mailers', to: "rails/mailers#index"
  get '/rails/mailers/*path', to: "rails/mailers#preview"


end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of :city, :state, :street, :zip

  belongs_to :location

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  validates_presence_of :destination, :travel_method

  belongs_to :trip
  has_many :addresses

  def self.travel_methods
    ['walk', 'fly', 'drive', 'train']
  end

end

app/models/trip.rb
class Trip < ApplicationRecord
  validates_presence_of :name

  belongs_to :user
  has_many :locations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :trips

  after_create :action_mailer

  # validates_presence_of :admin, default: false

  def display_name
    "#{first_name} #{last_name}"
  end

  def self.from_omniauth(auth)
    where(uid: auth.uid, provider: auth.provider).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def action_mailer
    SignupMailer.new_signup(self).deliver
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_location
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @title = 'Address'
    @address = @location.addresses.first
    flash[:info] = 'Welcome To The Location Address'
  end

  def show
    @title = 'Address'
  end

  def new
    @title = 'Add New Address'
    @address = Address.new
  end

  def create
    @address = @location.addresses.new(address_params)
      if @address.save
        flash[:success] = 'Address Created'
        redirect_to location_address_path(@location, @address)
      else
        flash[:error] = 'Please Try Again'
        render :new
      end
  end

  def edit
    @title = 'Edit This Address'
  end

  def update
    if @address.update(address_params)
      flash[:success] = 'Address Updated'
      redirect_to location_address_path(@location, @address)
    else
      flash[:error] = 'Please Try Again'
      render :edit
    end
  end

  def destroy
    @address.destroy
    redirect_to location_addresses_path(@location)
  end

  private
    def address_params
      params.require(:address).permit(:city, :state, :street, :zip, :location_id)
    end

    def set_location
     @location = Location.find(params[:location_id])
    end

    def set_address
      @address = @location.addresses.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:admin, :first_name, :last_name, :email, :password, :password_confirmation])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @title = 'Trip Locations'
    @locations = @trip.locations
    flash[:info] = 'Welcome To The Trip Locations'
  end

  def show
    @title = @location.destination
  end

  def new
    @title = 'Add New Location'
    @travel_methods =   Location.travel_methods
    @location = Location.new
  end

  def create
    @location = @trip.locations.new(location_params)
      if @location.save
        flash[:success] = 'New Location Created'
        redirect_to trip_location_path(@trip, @location)
      else
        flash[:error] = 'Please Try Again'
        @travel_methods = Location.travel_methods
        render :new
      end
  end

  def edit
    @title = 'Edit This Location'
    @travel_methods = Location.travel_methods
  end

  def update
    if @location.update(location_params)
      flash[:success] = 'Location Updated'
      redirect_to trip_location_path(@trip, @location)
    else
      flash[:error] = 'Please Try Again'
      @travel_methods = Location.travel_methods
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to trip_locations_path(@trip)
  end

  private
    def location_params
      params.require(:location).permit(:destination, :travel_method, :trip_id)
    end

    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_location
      @location = @trip.locations.find(params[:id])
    end
end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController
  def new
    @title = 'Add a Newsletter'
  end

  def create
    NewsletterJob.perform_later({
                                 emails: params[:emails],
                                 subject: params[:subject],
                                 newsletter: params[:newsletter]
                                })
    flash[:success] = 'Newsletter Sent!'
    redirect_to new_newsletter_path
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @title = 'Trips'
    @trips = current_user.trips.paginate(page: params[:page], per_page: 3)
    flash[:info] = 'Welcome To The Trip Tracker'
  end

  def show
    @title = current_user.trips.name
    @locations = @trip.locations.all
  end

  def new
    @title = 'Add New Trip'
    @trip = current_user.trips.new
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.save
      flash[:success] = 'New Trip Created'
      redirect_to trip_path(@trip)
    else
      flash[:error] = 'Please Try Again'
      render :new
    end
  end

  def edit
    @title = 'Edit This Trip'
  end

  def update
    if @trip.update(trip_params)
      flash[:success] = 'Trip Updated'
      redirect_to trip_path(@trip)
    else
      flash[:error] = 'Please Try Again'
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private
    def trip_params
      params.require(:trip).permit(:name)
    end

    def set_trip
      @trip = Trip.find(params[:id])
    end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.create(user_params)
    SignupMailer.new_signup(user).deliver
    redirect_to :root
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= form_for [@location, @address] do |f| %>
  <div class='field margin'>
    <div class='card'>
      <%= f.label :street %>
      <%= f.text_field :street %>
    </div>

    <div class='card'>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>

    <div class='card'>
      <%= f.label :state %>
      <%= f.text_field :state %>
    </div>

    <div class='card'>
      <%= f.label :zip %>
      <%= f.text_field :zip %>
    </div>
  </div>

  <%= f.submit 'Submit', class: 'btn orange white-text margin'%>
<% end %>

app/views/addresses/edit.html.erb
<%= render(partial: 'form') %>
<%= link_to 'Back', :back, class: 'btn orange white-text margin' %>

app/views/addresses/index.html.erb
<% if @address.nil? %>   
    <h3>No Address Found</h3>
    <%= link_to 'New Address', new_location_address_path(@location), class: 'btn orange white-text margin' %>
<% else %>
    <div class='field margin'>
      <div class='card'>
        <h4><%= @address.street %></h4>
        <h4><%= @address.city %>, <%= @address.state %> <%= @address.zip %></h4>
        <%= link_to 'Show', location_address_path(@location, @address), class: 'btn orange white-text' %>
      </div>
    </div>
<% end %>
<%= link_to 'Back', trip_locations_path(@location), class: 'btn orange white-text margin' %>
<%= link_to 'Home', :root, class: 'btn orange white-text margin' %>

app/views/addresses/new.html.erb
<%= render(partial: 'form') %>
<%= link_to 'Back', :back, class: 'btn orange white-text margin' %>

app/views/addresses/show.html.erb
<ul class='field margin'>
  <h3 class='card'>
    <li>Street: <%= @address.street %> </li>
  </h3>
  <h3 class='card'>
    <li>City: <%= @address.city %> </li>
  </h3>
  <h3 class='card'>
    <li>State: <%= @address.state %> </li>
  </h3>
  <h3 class='card'>
    <li>Zip: <%= @address.zip %> </li>
  </h3>
    <li>
      <%= link_to 'Edit', edit_location_address_path(@location, @address), class: 'btn orange white-text margin' %>
      <%= link_to 'Delete', location_address_path(@location, @address), method: :delete, data: {confirm: 'Really Delete?'},
          class: 'btn orange white-text margin' %>
    </li>
</ul>

<%= link_to 'Back', location_addresses_path(@location), class: 'btn orange white-text margin' %>

app/views/home/index.html.erb
<h1 class='field'>
  <div class='card'>
   Welcome <%= current_user.display_name %>
  </div>
</h1>

<%= link_to 'Your Trips', trips_path, class: 'btn orange white-text' %>

app/views/signup/index.html.haml
%h2 Sign up for the newsletter!
%hr
= form_for @user do |f|
  = f.label :name
  = f.text_field :name
  = f.label :email 
  = f.email_field :email
  = f.submit