config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :trips do
    resources :locations
  end
 
  resources :locations do
    resources :addresses
  end

  resources :signup

  resources :newsletter, only: [:new, :create]

  get '/rails/mailers', to: "rails/mailers#index"
  get '/rails/mailers/*path', to: "rails/mailers#preview"


end

app/models/location.rb
class Location < ApplicationRecord
  validates_presence_of :destination, :travel_method

  belongs_to :trip
  has_many :addresses

  def self.travel_methods
    ['walk', 'fly', 'drive', 'train']
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @title = 'Trip Locations'
    @locations = @trip.locations
    flash[:info] = 'Welcome To The Trip Locations'
  end

  def show
    @title = @location.destination
  end

  def new
    @title = 'Add New Location'
    @travel_methods =   Location.travel_methods
    @location = Location.new
  end

  def create
    @location = @trip.locations.new(location_params)
      if @location.save
        flash[:success] = 'New Location Created'
        redirect_to trip_location_path(@trip, @location)
      else
        flash[:error] = 'Please Try Again'
        @travel_methods = Location.travel_methods
        render :new
      end
  end

  def edit
    @title = 'Edit This Location'
    @travel_methods = Location.travel_methods
  end

  def update
    if @location.update(location_params)
      flash[:success] = 'Location Updated'
      redirect_to trip_location_path(@trip, @location)
    else
      flash[:error] = 'Please Try Again'
      @travel_methods = Location.travel_methods
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to trip_locations_path(@trip)
  end

  private
    def location_params
      params.require(:location).permit(:destination, :travel_method, :trip_id)
    end

    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_location
      @location = @trip.locations.find(params[:id])
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for [@trip, @location] do |f| %>
  <div class='field margin'>
    <div class='card'>
      <%= f.label :destination %>
      <%= f.text_field :destination %>
    </div>

    <div class='card'>
      <%= f.label :travel_method %>
      <%= f.select :travel_method, (@travel_methods), {}, class: 'browser-default' %>
    </div>
  </div>
  
  <%= f.submit 'Submit', class: 'btn orange white-text margin'%>
<% end %>

app/views/locations/edit.html.erb
<%= render(partial: 'form') %>
<%= link_to 'Back', trip_locations_path(@trip), class: 'btn orange white-text margin' %>

app/views/locations/index.html.erb
<div class='field margin'>
  <% @locations.each do |location| %>
    <div class='card'>
      <h4><%= location.destination %></h4>

      <h5><%= location.travel_method %></h5>

      <%= link_to 'Show', trip_location_path(@trip, location), class: 'btn orange white-text' %>

      <%= link_to 'Address', location_addresses_path(location), class: 'btn orange white-text' %>
    </div>
  <% end %>
</div>

<%= link_to 'New Trip Location', new_trip_location_path(@trip, @location), class: 'btn orange white-text margin' %>

<%= link_to 'Back', :back, class: 'btn orange white-text margin' %>

app/views/locations/new.html.erb
<%= render(partial: 'form') %>
<%= link_to 'Back', trip_locations_path(@trip), class: 'btn orange white-text margin' %>

app/views/locations/show.html.erb
<ul class='field margin'>
  <h3 class='card'>
    <li>Name: <%= @location.destination %> </li>
  </h3>
    <li>
      <%= link_to 'Edit', edit_trip_location_path(@trip, @location), class: 'btn orange white-text' %>
      <%= link_to 'Delete', trip_location_path(@trip, @location), method: :delete, data: {confirm: 'Really Delete?'}, class: 'btn orange white-text' %>
    </li>
</ul>

<%= link_to 'Back', trip_locations_path(@trip), class: 'btn orange white-text margin' %>